org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=false
org.gradle.caching=true
mod_id=colonyloom
mod_name=Colonyloom
mod_version=0.1.0
mod_group_id=io.github.kpuctajluk.colonyloom
neo_version=21.1.252
neoform_version=1.21.1-20240808.144430
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
